### ISSUE TITLE
installation issue.

### ISSUE THREAD

**Issue by Dj-jom2x** [MagicStack/uvloop#194] opened 2018-08-09 12:55 UTC
**uvloop: none**
**python 3.6.6**
**termux arm64**

why does it says 
```
$ pip install uvloop
Collecting uvloop
  Using cached https://files.pythonhosted.org/packages/5c/37/6daa39aac42b2deda6ee77f408bec0419b600e27b89b374b0d440af32b10/uvloop-0.11.2.tar.gz
Installing collected packages: uvloop
  Running setup.py install for uvloop ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-aqvzvzn3/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-ngqe1bvo/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/__init__.py -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/_patch.py -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/_testbase.py -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/_noop.py -> build/lib.linux-aarch64-3.6/uvloop
    running egg_info
    writing uvloop.egg-info/PKG-INFO
    writing dependency_links to uvloop.egg-info/dependency_links.txt
    writing top-level names to uvloop.egg-info/top_level.txt
    reading manifest file 'uvloop.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/.git'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/docs'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/img'
    writing manifest file 'uvloop.egg-info/SOURCES.txt'
    copying uvloop/cbhandles.pxd -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/cbhandles.pyx -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/dns.pyx -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/errors.pyx -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/loop.c -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/loop.pxd -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/loop.pyx -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/pseudosock.pyx -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/request.pxd -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/request.pyx -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/server.pxd -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/server.pyx -> build/lib.linux-aarch64-3.6/uvloop
    copying uvloop/sslproto.pyx -> build/lib.linux-aarch64-3.6/uvloop
    creating build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/async_.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/async_.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/basetransport.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/basetransport.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/check.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/check.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/handle.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/handle.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/idle.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/idle.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/pipe.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/pipe.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/poll.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/poll.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/process.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/process.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/stream.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/stream.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/streamserver.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/streamserver.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/tcp.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/tcp.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/timer.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/timer.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/udp.pxd -> build/lib.linux-aarch64-3.6/uvloop/handles
    copying uvloop/handles/udp.pyx -> build/lib.linux-aarch64-3.6/uvloop/handles
    creating build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/__init__.py -> build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/compat.h -> build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/consts.pxi -> build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/debug.h -> build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/debug.pxd -> build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/python.pxd -> build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/stdlib.pxi -> build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/system.pxd -> build/lib.linux-aarch64-3.6/uvloop/includes
    copying uvloop/includes/uv.pxd -> build/lib.linux-aarch64-3.6/uvloop/includes
    running build_ext
    error: [Errno 2] No such file or directory: './configure': './configure'
```
this is the first time i have a problem with installing packages on py.. others seems to install just fine.. but uvloop throw this error.

**Comment by 1st1** [comment] 2018-08-09 13:27
Are you trying to install it on Android? If so it's not officially supported and I have no way to test what's going on. And I can't reproduce this error on my machine. Most likely you don't really need uvloop on android anyways, vanilla asyncio should work just fine.

**Comment by elprans** [comment] 2018-08-09 13:41
Installing uvloop from a source distribution requires building the bundled libuv, which requires a working `/bin/sh`, GNU make, and a C compiler none of which are guaranteed to be present on Android.

**Comment by Dj-jom2x** [comment] 2018-08-10 01:36
hmm good morning sir :) I believe termux can do that. I already compiled ffmpeg, lavalink, libopus, quickbms, cython

i believe the configure is missing while copying..

so....

I build uvloop straight from your repo guys
clone repo
pkg install automake
pkg install cython
pkg install libtools or libtool i forgot.
then replace all bin/sh/ into sh only
because on termux bin/sh is invalid..

also this configure.ac that generates configure..  i don't know how to edit that ac


so..

i did this clever thing
below touch commands
```
with open( f"{LIBUV_BUILD_DIR}/configure", 'r') as f:
            fdata = f.read()
        fdata = fdata.replace("/bin/sh","sh")
        with open( f"{LIBUV_BUILD_DIR}/configure", 'w') as t:
            t.write(fdata)
```
then install it ... pip install .

```
$ pip install .
Processing /data/data/com.termux/files/home/uvloop
Installing collected packages: uvloop
  Running setup.py install for uvloop ... done
Successfully installed uvloop-0.12.0.dev0
$
```

btw my solution above is not the answer of the question I make :)

i use the pip install uvloop then it will return
 ./configure is no such directory

but on the fresh from the hub i only need to edit /bin/sh to sh only, else i got this

./configure: 1: eval: /bin/sh: not found
    configure: WARNING: 'missing' script is too old or missing

**Comment by 1st1** [comment] 2018-08-14 15:05
I'm going to close this as I don't see anything actionable for myself here. But please submit a PR if you know how to improve `setup.py`.

**Closed by 1st1** 2018-08-14 15:05 UTC
Labels: question
