### ISSUE TITLE
stream.pyx:784 _on_read function pass more than one request to a read callback function

### ISSUE THREAD

**Issue by 0x161e-swei** [MagicStack/uvloop#141] opened 2018-05-07 02:08 UTC
* **uvloop version**:
0.9.1.
* **Python version**:
3.5.2
* **Platform**:
Ubuntu 16.04.4 with kernel version 4.13.0-39-generic
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:
Yes, the error I got is still persistent.

I am using [sc2682cornell](https://github.com/sc2682cornell/wrk2) version of wrk2 to test sanic servers, which uses uvloop 0.9.1.

It turns out that when the call back function provided by sanic is called from uvloop at handles/stream.pyx:563,
the data object passed to that function consists of multiple requests like following:

```
b'GET /test/ HTTP/1.1\r\nHost: 10.157.90.165:8080\r\n\r\nGET /test/ HTTP/1.1\r\nHost: 10.157.90.165:8080\r\n\r\n'
```
The client side, however, only sends one request at at time, specifically, each write systemcall sends one get request.

Could this be a feature or a bug from uvloop?

Please find more details at the issue at [sanic#1211](https://github.com/channelcat/sanic/issues/1211)

**Comment by 1st1** [comment] 2018-05-07 02:51
Definitely not feature, but I'm not sure it's a bug of uvloop and not of sc2682cornell version of wrk. Would appreciate you investigating this further.

**Comment by 0x161e-swei** [comment] 2018-05-07 02:57
I was able to reproduce this with server provided in [vmbench](https://github.com/MagicStack/vmbench/blob/master/servers/asyncio_http_server.py) with the same load generator.

This server was configured to use uvloop and httptools.
Simply printing from `data_received` function gives me this:
```
b'GET /256 HTTP/1.1\r\nHost: 10.157.90.165:25000\r\n\r\nGET /256 HTTP/1.1\r\nHost: 10.157.90.165:25000\r\n\r\nGET /256 HTTP/1.1\r\nHost: 10.157.90.165:25000\r\n\r\n'
```

It is unlikely that this is a bug of sc2682cornell since the same load generator works perfectly with a Flask server.

**Comment by 0x161e-swei** [comment] 2018-05-07 03:27
Also profiled using wireshark, all the HTTP packets captured have a single request.

**Comment by 1st1** [comment] 2018-05-07 03:29
Do you think you can create a failing unit test?

**Comment by 1st1** [comment] 2018-05-07 03:29
Also, can you reproduce this with vanilla asyncio?

**Comment by 0x161e-swei** [comment] 2018-05-07 04:09
Interestingly I can indeed reproduce this with asyncio with httptools using the same server code at [vmbench](https://github.com/MagicStack/vmbench/blob/master/servers/asyncio_http_server.py)

As of unit test. I am afraid I cannot.

**Comment by 1st1** [comment] 2018-05-07 04:11
Maybe this is an httptools bug then.

**Comment by 0x161e-swei** [comment] 2018-05-07 04:18
If I understand this correctly, the `data_received` function is called before the httpparser from httptools is even involved, right?

**Comment by 0x161e-swei** [comment] 2018-05-07 05:36
ok. now it makes sense to me.
So a data object in `data_received` function consisting of multiple requests is an expected behavior if the client is using HTTP pipelining?

**Comment by 1st1** [comment] 2018-05-07 15:30
> So a data object in data_received function consisting of multiple requests is an expected behavior if the client is using HTTP pipelining?

Probably. I never implemented support for HTTP pipelining but I imagine it works in this way: concatenate a bunch of HTTP requests and let the client parse them. Since HTTP pipelining isn't used widely, I guess it's a non-issue for sanic.

I'm going to close this issue since this isn't a uvloop (or even asyncio) bug.

**Closed by 1st1** 2018-05-07 15:30 UTC
