### ISSUE TITLE
uvloop + aiohttp: AttributeError: '_GatheringFuture' object has no attribute '_blocking'

### ISSUE THREAD

**Issue by smortus** [MagicStack/uvloop#56] opened 2016-10-13 15:36 UTC
* **uvloop version**:
uvloop (0.5.3)
aiohttp (1.0.3)

* **python version**:
Python 3.5.2+

* **platform**:
Linux ubuntu 4.8.0-14-generic #15-Ubuntu SMP Tue Sep 20 22:02:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Code:
```
import asyncio

from aiohttp import web
import uvloop


asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())


async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

app = web.Application()
app.router.add_get('/', handle)
app.router.add_get('/{name}', handle)

web.run_app(app)
```

traceback:
```
Exception in callback Task._step
handle: <Handle Task._step>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run (uvloop/loop.c:38343)
  File "uvloop/task.pyx", line 159, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:99783)
AttributeError: '_GatheringFuture' object has no attribute '_blocking'
```

**Comment by 1st1** [comment] 2016-10-15 00:00
I can't reproduce this. It's really weird that `_GatheringFuture` doesn't have the `_blocking` attribute.

**Comment by mstyvane** [comment] 2016-10-17 10:02
Hi @1st1, I was about to file the same bug. Just ran into this. Also this doesn't release the interpreter, I have to use `kill -9` 

- Python 3.6.0b1
- asyncpg==0.5.4
- uvloop==0.5.3

Code:

    import asyncio

    import uvloop
    import asyncpg

    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
    loop = asyncio.get_event_loop()

    statement = 'select id from dict.operators where country_id = ANY($1::varchar[])'

    dns = 'postgres://postgres:password@127.0.0.1:5432/test'

    async def get_id(pool, statement, countries):
        async with pool.acquire() as con:
            stmt = await con.prepare(statement)
            return await stmt.fetch(countries) 

    async def run(dns, countries):
        async with asyncpg.create_pool(dns) as pool:
            print(await get_id(pool, countries))
  

    loop.run_until_complete(run(dns, ['AF', 'CI', 'SD', 'SS']))

Which returns the result with a traceback:
   
    [<Record id=6>, <Record id=7>, <Record id=8>, <Record id=9>, <Record id=10>, <Record id=11>, <Record id=146>, <Record id=147>, <Record id=148>, <Record id=149>, <Record id=702>, <Record id=703>, <Record id=704>, <Record id=705>, <Record id=746>, <Record id=747>]

    Exception in callback <built-in method _wakeup of Task object at 0x7f6a9260f6d0>
    handle: <Handle Task._wakeup>
    Traceback (most recent call last):
    File "uvloop/cbhandles.pyx", line 57, in uvloop.loop.Handle._run (uvloop/loop.c:38264)
    File "uvloop/task.pyx", line 202, in uvloop.loop.BaseTask._wakeup (uvloop/loop.c:101008)
    File "uvloop/task.pyx", line 195, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:100711)
    File "uvloop/task.pyx", line 159, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:99772)
    AttributeError: '_GatheringFuture' object has no attribute '_blocking'

**Comment by 1st1** [comment] 2016-10-17 21:47
@smortus Are you sure you used python 3.5 and not 3.6?
@mstyvane I'm looking into this...

**Comment by 1st1** [comment] 2016-10-17 22:06
The reason I can't reproduce this is because this has been fixed in 0.5.4. Please try it out.

**Comment by smortus** [comment] 2016-10-18 04:33
Confirm. With uvloop 0.5.4 app running normal.

**Comment by 1st1** [comment] 2016-10-18 15:56
Alright, closing the issue then!

**Closed by 1st1** 2016-10-18 15:56 UTC
