### ISSUE TITLE
Pathlib throws "Bad file descriptor", but only with `uvloop`.

### ISSUE THREAD

**Issue by decorator-factory** [MagicStack/uvloop#414] opened 2021-05-22 15:30 UTC
* **uvloop version**: 0.15.3
* **Python version**: 3.9.5
* **Platform**: Manjaro, kernel is 5.10.42-1
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: no
* **Does uvloop behave differently from vanilla asyncio? How?**: without `uvloop`, the script works just fine.

When spawning processes and creating file, an `OSError: [Errno 9] Bad file descriptor` sometimes appears.

Script and output: https://gist.github.com/decorator-factory/6b5276ab5fb87f4c009f1d22dc4b20a9

Sometimes it also just hangs, with 0 CPU consumption. When I press CTRL+C, I get this traceback: https://gist.github.com/decorator-factory/888a584cbc4d44600ea62f5e7e344b66

Sometimes it completes successfully.

**Comment by graingert** [comment] 2021-07-13 18:59
Is this fixed by #408 ?

**Comment by decorator-factory** [comment] 2021-07-13 20:26
> Is this fixed by #408 ?

Doesn't seem to be, I just tested on 0.15.3, and I get the same results

**Comment by decorator-factory** [comment] 2021-08-12 11:04
Update: on 16.0 I no longer get the core dump, but the 'bad file descriptor' persists

**Comment by th3hamm0r** [comment] 2021-09-29 11:33
Fyi: I don't know if this is related to that issue, but we see similar log entries of `Error while closing socket [Errno 9] Bad file descriptor` logged by gunicorn in our django setup with gunicorn, uvicorn, uvloop, websockets, when the server is shutting down. Tested with the latest version of uvloop, uvicorn etc.

**Comment by shughes-uk** [comment] 2022-05-05 20:23
We are seeing this a lot with `asyncio.create_subprocess_exec` . Guincorn + uvicorn workers + uvloop+ websockets

```
proc = await asyncio.create_subprocess_exec(
File "/opt/conda/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
transport, protocol = await loop.subprocess_exec(
File "uvloop/loop.pyx", line 2793, in subprocess_exec
File "uvloop/loop.pyx", line 2751, in __subprocess_run
File "uvloop/handles/process.pyx", line 597, in uvloop.loop.UVProcessTransport.new
File "uvloop/handles/process.pyx", line 127, in uvloop.loop.UVProcess._init
OSError: [Errno 9] Bad file descriptor
```

**Comment by graingert** [comment] 2022-05-11 10:24
@decorator-factory can you try my patch https://github.com/MagicStack/uvloop/pull/466 ?

**Comment by shughes-uk** [comment] 2022-05-11 15:43
Yes I’ll putt this through it’s paces and report back

**Comment by decorator-factory** [comment] 2022-05-18 07:17
@graingert Yes this fixes it for me. Thanks for the fix

**Comment by cbay** [comment] 2022-05-19 07:26
@graingert I can confirm that your one-liner fixes the issue for me as well. I've been running my application for the last few days with your fix, and I haven't had any `OSError: [Errno 9] Bad file descriptor` since (I had dozens every day before).

Thanks!

**Closed** 2022-07-17 15:22 UTC

**Comment by pplmx** [comment] 2023-10-26 06:41
The same issue to me, but it's only occurred on my k8s deployment.
Here is [my repo](https://github.com/pplmx/LearningFastAPI), `make k` to deploy it by k8s to reproduce the issue.
