### ISSUE TITLE
uvloop and web frameworks problem

### ISSUE THREAD

**Issue by alexeykhit** [MagicStack/uvloop#123] opened 2018-01-09 11:06 UTC
* **uvloop version**: 0.5.0 or 0.8.1 or 0.9.1
* **Python version**: 3.5.2
* **Platform**: Ubuntu 16.04.3 LTS
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: no

python web frameworks with uvloop perform a requests with higher priority than return the result of finished requests. Active requests accumulate and the result to the user is delayed.

There is no problem with the standard loop.

I checked `aiohttp` and `sanic` with default loop and `aiohttp`, `sanic` and `japronto` with `uvloop`.

I sent multiple requests to the server. Each of them was performed for 5 seconds. I used `time.sleep`, but it could be a real long running code.

In the case of a default loop results returned in 5, 10, 15, 20 etc. seconds.
But with uvloop results returned in 5, 20, 20, 20 seconds or 5, 15, 15, 20 seconds.

I tried to send requests with delays. The result is the same.

My research: https://github.com/alexeykhit/pyasyncweb-tests

**Comment by 1st1** [comment] 2018-01-09 11:44
Please add some 'awaits' in your code where you call `time.sleep`. Otherwise the scheduler will simply call all blocking callbacks in a row and what you see is entirely reasonable.  I'll say more: there are no guarantees that vanilla asyncio will keep it's current behaviour w.r.t. how blocking code is exactly being executed.

**Comment by alexeykhit** [comment] 2018-01-09 13:20
I add custom awaits in my code. Vanilla asyncio has same problems only when I use **await after time.sleep**.

```
async def get_sync(request):
    if 'before' in request.query:
        await asyncio.sleep(float(request.query.get('before')))
    time.sleep(float(request.query.get('sleep', 5)))
    if 'after' in request.query:
        await asyncio.sleep(float(request.query.get('after')))
    return web.Response(text='OK')
```

Maybe problem with `AbstractEventLoop.create_server` logic? Maybe `uvloop` has some `await` (code switch) before return result and vanilla asyncio don't?

**Comment by alexeykhit** [comment] 2018-01-09 17:08
@1st1 I was right about problem in `AbstractEventLoop.create_server`.

I write simple TCP Server:
https://github.com/alexeykhit/pyasyncweb-tests/blob/master/main_builtin.py
https://github.com/alexeykhit/pyasyncweb-tests/blob/master/main_builtin_uvloop.py

And make new tests:
https://github.com/alexeykhit/pyasyncweb-tests#test2

**Default loop** return result right after each `self.transport.write/self.transport.close`.
But **uvloop** return result after last `self.transport.write/self.transport.close`.

**Comment by 1st1** [comment] 2018-05-23 22:53
I'm going to close this as "not a bug". There are no guarantees on how exactly callbacks are scheduled by event loops and I don't see any serious discrepancy with uvloop here. Feel free to reopen if you can find more examples.

**Closed by 1st1** 2018-05-23 22:53 UTC
