### ISSUE TITLE
asyncio.get_child_watcher Not Working

### ISSUE THREAD

**Issue by NotSoSuper** [MagicStack/uvloop#64] opened 2016-12-08 16:43 UTC
* **uvloop version**: Latest PIP
* **python version**: Python 3.5.2
* **platform**: Ubuntu Server 14.04

Using uvloop and asyncio.SubprocessProtocol to run shell commands asynchronously, these create zombie processes which are not garbage collected properly unless you run `asyncio.get_child_watcher().attach_loop(loop)`.

Since I am using uvloop as the event loop policy, for some reason it is not calling the unix_events function from the asyncio module and returning this error:

`Traceback (most recent call last):
File "/root/discord/bot0.py", line 18, in <module>
 bot = NotSoBot(loop=loop, shard_id=shard_id, shard_count=shard_count, dev_mode=dev_mode, max_messages=10000)
File "/root/discord/bot.py", line 126, in __init__
  asyncio.get_child_watcher().attach_loop(self.loop)
File "/usr/lib/python3.5/asyncio/events.py", line 647, in get_child_watcher
  return get_event_loop_policy().get_child_watcher()
File "/usr/lib/python3.5/asyncio/events.py", line 538, in get_child_watcher
  raise NotImplementedError
NotImplementedError`

The function is only available for unix systems which I am on but with uvloop it doesn't work.

**Comment by 1st1** [comment] 2016-12-08 16:46
You shouldn't use `asyncio.get_child_watcher().attach_loop(loop)` with uvloop -- uvloop doesn't have child watchers.

Are you saying that running shell commands with uvloop creates zombies? Can you share your code?

**Comment by 1st1** [comment] 2016-12-08 21:15
What kind of commands are you trying to execute? Short/long living?
Can you move `transport.close()` into a `finally` block so that it's guaranteed to be called?

**Comment by NotSoSuper** [comment] 2016-12-08 21:16
Most of the commands are usually `ffmpeg` which takes only a few seconds, others are stuff like `cowsay`, so nothing that takes too long. I'll try that, thanks.

**Comment by 1st1** [comment] 2016-12-08 21:25
Yeah, so far I can't reproduce this :(  It would be extremely helpful if you could provide a complete minimal program that reproduces the issue.

**Comment by NotSoSuper** [comment] 2016-12-08 21:38
Yeah, just tried this and it never ends: https://gist.github.com/NotSoSuper/df228346bc9645d105216d9f8c2fe38b

Thing I can't explain here is that in my main projects code the function returns the result from `cowsay` or etc but this script won't return anything, not sure..

**Comment by 1st1** [comment] 2016-12-08 21:48
> Yeah, just tried this and it never ends: https://gist.github.com/NotSoSuper/df228346bc9645d105216d9f8c2fe38b

Exits normally (well, with exceptions on `set_result(True)` being called more than once) for me on Mac OS and Gentoo. Strange.

> Edit: Ending the python repl session returned 'done'

**Comment by NotSoSuper** [comment] 2016-12-08 22:02
Yeah, putting it into a python script file and running it returned the same but I'm getting zombie processes from somewhere when this is run.

**Comment by 1st1** [comment] 2016-12-16 17:25
Have you been able to fix this/find the problem?

**Comment by 1st1** [comment] 2016-12-24 21:39
Ok, closing this one as I'm still unable to reproduce on both Linux and OS X. Feel free to reopen.

**Closed by 1st1** 2016-12-24 21:39 UTC
