### ISSUE TITLE
'coroutine' object is not iterable

### ISSUE THREAD

**Issue by alxpy** [MagicStack/uvloop#122] opened 2017-12-06 09:01 UTC
* **uvloop version**: 0.9.1
* **Python version**: 3.6
* **Platform**: Ubuntu Xenial

Version 0.9.1:
I got an error
```
 File "/app/app/<***>/utils.py", line 35, in <***>
    async with app['client_session'].get(url) as response:
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 402, in connect
    proto = yield from self._create_connection(req)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 748, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 831, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 796, in _wrap_create_connection
    return (yield from self._loop.create_connection(*args, **kwargs))
TypeError: 'coroutine' object is not iterable
```

Version 0.8.1:
Not reproduced

The error does not depend on other libraries.

**Comment by Sherlock-Holo** [comment] 2017-12-06 13:41
I forgot if I met this problem, but I guess the build script about uvloop
has some problems because I rewrite the Arch pkgbuild about uvloop and
fixed some problems like yours

Alex Kuzmenko <notifications@github.com> 于 2017年12月6日周三 17:01写道：

**Comment by 1st1** [comment] 2017-12-07 02:48
Did you install uvloop via pip? Do you use any other packages that are compiled with Cython?

**Comment by alxpy** [comment] 2017-12-07 14:25
yes, we use pip. and we have other packages (for example: `aiohttp`, `cChardet`)

**Comment by oliwarner** [comment] 2017-12-13 09:57
I get the same with Python 3.6 (stock cpython, Ubuntu 17.10) with a pip-installed uvloop

**Comment by achimnol** [comment] 2017-12-25 05:16
Another bump here with Python 3.6 on Ubuntu as well.

**Comment by frnkvieira** [comment] 2018-01-16 13:10
Same here. (Python 3.6.4, Ubuntu 17.10)

**Comment by Urahara** [comment] 2018-01-23 13:31
I facing this problem too, using aiohttp, any workaround? Snippet of my code:

```
            try:
                async with async_timeout.timeout(15):
                    async with self.session.get('http://example.com') as resp:
                        response = resp
                        break
            except Exception as e:
```

**Comment by 1st1** [comment] 2018-01-23 16:02
I suspect that the bug is in Cython.  Waiting for its next release to fix things.

**Comment by asvetlov** [comment] 2018-01-23 19:28
Have observed the same problem in our production code.
Surprisingly plain aiohttp example (without our straightforward but complex tooling built on top of aiohttp session) worked fine.

I was unable to pin down the minimal reproducible test case unfortunately.

**Comment by dyeray** [comment] 2018-01-27 23:28
I'm having the exact same issue on my project, in this case when creating an asyncio_redis connection. It only happens if I import BeautifulSoup at the module level. I'm importing it at the function level as a workaround.

**Comment by codeadict** [comment] 2018-01-28 18:12
I have this issue too with aiohttp

**Comment by 1st1** [comment] 2018-01-28 18:14
Again, it looks like this is a regression in Cython.  Try installing earlier uvloop versions, we'll fix it with the next Cython release.

**Comment by 1st1** [comment] 2018-03-01 18:20
A new `@cython.iterable_coroutine` decorator has been added to Cython, which should resolve this issue. Now waiting for the next release to happen.

**Comment by em1208** [comment] 2018-03-12 06:13
I have the same issue using uvloop 0.9.1 in python 3.5.2 with asyncio create_subprocess_exec. I hope this will be fixed soon!

**Comment by woyodb** [comment] 2018-03-21 06:11
**uvloop version:** 0.9.1
**Python version:** 3.6.4
**Platform**: Mac OS
I got the same issue, hope this to be fixed soon.

**Comment by achimnol** [comment] 2018-03-21 15:50
Cython 0.28 and 0.28.1 which includes the required patch is released now. :tada:
Ref: [The Cython 0.28.1 changelog](https://github.com/cython/cython/blob/0.28.1/CHANGES.rst)
@1st1 I think it is the time to update the binary package! :wink:

**Comment by 1st1** [comment] 2018-05-23 19:01
Fixed in master. Please test :)

**Closed by 1st1** 2018-05-23 19:01 UTC

**Comment by snenkov** [comment] 2020-07-01 18:34
I keep having this issue. I am using the latest `cpython` and `uvloop`. Any clues how I can fix this? : )

**Comment by 1st1** [comment] 2020-07-01 19:26
Not sure. Most likely it's unrelated to uvloop. I suggest debugging the line that causes this exception.

**Comment by wiedehopf** [comment] 2021-11-12 12:42
In case someone else gets this error message, just convert to async def / await ... that fixed the issue for me.
It's usually as simple as replacing like this:
```
@asyncio.coroutine
def somefunction:
    reader, writer = yield from asyncio.open_connection(self.host, self.port)
    yield from asyncio.sleep(60.0)

async def asdfasdf:
    reader, writer = await asyncio.open_connection(self.host, self.port)
    await asyncio.sleep(60.0)
```
