### ISSUE TITLE
Exception in callback Loop._read_from_self after signal

### ISSUE THREAD

**Issue by samuelcolvin** [MagicStack/uvloop#94] opened 2017-06-02 17:29 UTC
* **uvloop version**: `0.8.0` (pypi latest)
* **Python version**: 3.6.1 (via docker image `python:3.6-alpine`) and 3.6.2 running without docker
* **Platform**: ubuntu 17.04 & docker
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: yes

[arq](https://github.com/samuelcolvin/arq) has some fairly complex shutdown logic using signals. Today I tried using it with uvloop, everything went fine until shutdown when things seemed to break a lot.

See log below, I'm not sure what more information you need, let me know and I'll try to provide. The log before the error occurs kind of explains what's going on.

I get the same error calling `docker-compose down` with a docker setup or `ctrl+c` with arq running directly on the host.

Related arq issue https://github.com/samuelcolvin/arq/issues/47.

```
INFO arq.work got signal: SIGTERM, waiting for worker pid=24 to finish...
INFO arq.work pid=24, got signal proxied from main process, stopping...
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 52, in uvloop.loop.Handle._run (uvloop/loop.c:48414)
  File "uvloop/loop.pyx", line 242, in uvloop.loop.Loop._read_from_self (uvloop/loop.c:9481)
  File "uvloop/loop.pyx", line 253, in uvloop.loop.Loop._process_self_data (uvloop/loop.c:9726)
  File "uvloop/loop.pyx", line 267, in uvloop.loop.Loop._handle_signal (uvloop/loop.c:9912)
  File "/usr/local/lib/python3.6/site-packages/arq/worker.py", line 356, in handle_proxy_signal
    raise HandledExit()
arq.worker.HandledExit
WARNING arq.work pid=24, got signal: SIGALRM again, forcing exit
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 52, in uvloop.loop.Handle._run (uvloop/loop.c:48414)
  File "uvloop/loop.pyx", line 242, in uvloop.loop.Loop._read_from_self (uvloop/loop.c:9481)
  File "uvloop/loop.pyx", line 253, in uvloop.loop.Loop._process_self_data (uvloop/loop.c:9726)
  File "uvloop/loop.pyx", line 267, in uvloop.loop.Loop._handle_signal (uvloop/loop.c:9912)
  File "/usr/local/lib/python3.6/site-packages/arq/worker.py", line 370, in handle_sig_force
    raise ImmediateExit('force exit')
arq.worker.ImmediateExit: force exit
```

**Comment by 1st1** [comment] 2017-06-02 18:09
What do I need to do to replicate this?

**Comment by samuelcolvin** [comment] 2017-06-02 18:19
code `demo.py`:

```python
import asyncio
from arq import Actor, BaseWorker, concurrent

import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

class DemoActor(Actor):
    @concurrent
    async def foobar(self, a):
        print(a)

class Worker(BaseWorker):
    shadows = [DemoActor]

async def enqueue_jobs():
    d = DemoActor()
    await d.foobar('hello')
    await d.foobar('world')
    await d.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(enqueue_jobs())
```

run:
```
pip install arq uvloop
python demo.py  # enqueues some jobs, not necessary to cause the error but helps explain whats going on
arq demo.py # you should see the jobs execute
ctrl + c  # you should see the error
```

If you comment out the two uvloop lines it should work fine.

**Comment by samuelcolvin** [comment] 2017-06-02 18:29
(oh, and you need redis installed)

**Comment by samuelcolvin** [comment] 2017-07-12 09:33
@1st1 did you have a chance to look at this? Is there anything else I can do to help?

**Comment by 1st1** [comment] 2017-07-12 15:45
I'll try to find some time to look at all open uvloop issues sometime this week.

**Comment by 1st1** [comment] 2017-11-15 22:32
Why do you use `signal.signal` instead of `loop.add_signal_handler`?

**Comment by samuelcolvin** [comment] 2017-11-15 22:33
I guess my mistake, I'll try `add_signal_handler` and let you know whether that fixes it.

**Comment by 1st1** [comment] 2017-11-15 22:36
Where do you handle `HandledExit`? There's clearly some difference in how uvloop and vanilla asyncio dispatch the signal.  Using `add_signal_handler` API should workaround your issue, but I'd like to understand what's going on here anyways..

**Comment by samuelcolvin** [comment] 2017-11-15 22:37
https://github.com/samuelcolvin/arq/blob/master/arq/worker.py#L435

**Comment by 1st1** [comment] 2017-11-15 22:39
Right, that's what I thought. I'll try to figure out what's really going on here.

**Comment by 1st1** [comment] 2017-11-15 23:23
I think I figured this out.  You install a signal handler using `signal.signal()` API, which means that the event loop has no control over when and how the signal will be processed.

*With asyncio:*

It so happens that the signal arrives when we select on sockets [1].  Because that code isn't guarded with `try..except`, any exception there will stop the loop. That's why when your `SIGINT` handler raises a `HandledExit` error, the loop stops and the error propagates through the `worker.run_until_complete(log_redis_version=True)` line.

Now, it's not guaranteed that the signal arrives at that particular code location.  It might, for example, arrive at some other place where there's a `try..except` block.  In which case anything can happen, depending on how that block is written.

*With uvloop:*

uvloop intercepts and handles all signals asynchronously.  There's no signal handler registered with the `loop.add_signal_handler()` API, therefore, the exception is raised right in the uvloop internals.  But uvloop is a bit more resilient to errors than vanilla asyncio, so it simply logs that an unhandled error has happened.

While uvloop behaves differently from asyncio in this very case, it's only a matter of time until we guard 'selector.select()` in asyncio with a `try..except` block and `arq` stops working with vanilla asyncio.

*Options for fixing this:*

1. `HandledExit` should subclass `BaseException`.  Both `uvloop` and `asyncio` will not try to suppress it, so your program will work reliably.  This is a preferred option for `SIGINT` specifically, because you want it to break Python tight loops if they ever occur in your code.

2. Use `loop.add_signal_handler()` API and handle your signals in a graceful fashion, i.e. call `loop.stop()` etc.

I'm closing this issue as "not a bug".

[1] https://github.com/python/cpython/blob/v3.6.3/Lib/asyncio/base_events.py#L1390

**Closed by 1st1** 2017-11-15 23:23 UTC

**Comment by samuelcolvin** [comment] 2017-11-15 23:47
Thanks so much for the explanation.

I've started a PR https://github.com/samuelcolvin/arq/pull/73 to implement both your suggestions.

**Comment by 1st1** [comment] 2017-11-15 23:51
To be more specific: you should probably keep using `signal.signal()` for `SIGINT`, and `loop.add_signal_handler()` for other signals.  But in any case please take my advice with a grain of salt, I suggest you to experiment and see what works best. Correctly handling signals is super hard and there's no generic advice that works in all cases.

**Comment by samuelcolvin** [comment] 2017-11-15 23:55
I know signals are tricky. I built arq partly because libraries like rq handle signals in strange ways. :-)

They're made more difficult because it's virtually impossible to write proper tests for all cases.

I'll definitely test a lot manually before I release and updated with this change.
