### ISSUE TITLE
Error:      pipenv install uvloop==0.16 

### ISSUE THREAD

**Issue by anorprogrammer** [MagicStack/uvloop#483] opened 2022-07-26 21:47 UTC
```console
PS C:\Learning\Dev\bot> pipenv install uvloop==0.16
Installing uvloop==0.16...
Error:  An error occurred while installing uvloop==0.16!
Error text: Collecting uvloop==0.16
  Downloading uvloop-0.16.0.tar.gz (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 302.0 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-tf96ljio\uvloop_747aa0e6a558478c94c9279665217b00\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

This is likely caused by a bug in uvloop. Report this to its maintainers.
Installation Failed
```

**Comment by graingert** [comment] 2022-07-29 12:09
> uvloop does not support Windows at the moment

Duplicate of https://github.com/MagicStack/uvloop/issues/14

**Closed** 2022-09-13 14:12 UTC
